services:
  database:
    image: mariadb:latest #optionaly set specific version e.g. mariadb:10.7
    #image: mariadb:10.7
    ports:
      - "3307:3306"
    networks:
      - db-tier
    environment:
      #  MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_ROOT_PASSWORD: activeeon
      MYSQL_DATABASE: proactive
    container_name: myComposeMariaDB
    # Uncomment this to attach a volume for persistent data storage and adjust location as needed:
    #volumes:
    #- mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin" , "ping", "-h", "localhost", "--password=activeeon" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  sal:
    #Set up image to be used for SAL from https://hub.docker.com/r/activeeon/sal/tags
    image: activeeon/sal:test
    #image: activeeon/sal:k3s
    #image: activeeon/sal:dev
    #image: activeeon/sal:dev-2024-08-21
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      #Port for sal service
      - "8088:8080"
      #Port for sal-pda debugging service
      - "9001:9001"
    links:
      - "database:myComposeMariaDB"
    networks:
      - db-tier
    volumes:
      - ./scripts:/usr/local/tomcat/scripts
      - ./wait_for_db.sh:/usr/local/tomcat/bin/wait_for_db.sh

    environment:
      PROPERTIES_FILENAME: sal
      #Set up connection to ProActive server (PWS)
      #PWS_URL: <CHANGE_ME>
      #PWS_USERNAME: <CHANGE_ME>
      #PWS_PASSWORD: <CHANGE_ME>

      #---- trydev ------
      #PWS_URL: https://trydev.activeeon.com:8443/
      #PWS_USERNAME: barisic
      #PWS_PASSWORD: ProActive123

      #---- NREC - SANDBOX ------
      PWS_URL: http://158.37.66.40:8880/
      PWS_USERNAME: cd
      PWS_PASSWORD: 5rf0A@sj01=

      #---- NREC - PRODUCTION------
      #PWS_URL: http://158.37.66.119:8880/
      #PWS_USERNAME: admin
      #PWS_PASSWORD: FvRV98mF3Ar&mG

      #---- NREC - PRODUCTION------
      #PWS_URL: http://158.37.66.119:8880/
      #PWS_USERNAME: admin
      #PWS_PASSWORD: FvRV98mF3Ar&mG

      #---- NREC - KUBE------
      #PWS_URL: http://proactive-scheduler-service-web:8080/
      #PWS_USERNAME: admin
      #PWS_PASSWORD: activeeon

      #---- AE - KUBE------
      #PWS_URL: http://kube.activeeon.com:32000//
      #PWS_USERNAME: admin
      #PWS_PASSWORD: activeeon

      #----LOCAL------
      #PWS_URL: http://192.168.56.1:8080/
      #PWS_USERNAME: admin
      #PWS_PASSWORD: admin

      DB_USERNAME: root
      #DB_PASSWORD: PASSWORD
      DB_PASSWORD: activeeon
      DB_DRIVER_CLASSNAME: org.mariadb.jdbc.Driver
      DB_PORT: 3306
      DB_HOSTNAME: myComposeMariaDB
      DB_URL: jdbc:mariadb://myComposeMariaDB:3306/proactive
      DB_PLATFORM: org.hibernate.dialect.MariaDB53Dialect
      JPDA_ADDRESS: 9001
      JPDA_TRANSPORT: dt_socket

    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /usr/local/tomcat/bin/wait_for_db.sh && \
      if [ -f /usr/local/tomcat/bin/wait_for_db.sh ]; then /usr/local/tomcat/bin/wait_for_db.sh; fi && \
      export JPDA_OPTS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:9001' && \
      catalina.sh jpda run"
    ]
    container_name: myComposeSAL

networks:
  db-tier: {}

  #Uncomment this part to include volume for peristant data storage
  #volumes:
  #mariadb_data: {}